- CHANGELOG.md
- package.json
- src/preact10-rst.ts
- src/shallow-render-utils.ts
- test/integration_test.tsx
- test/preact-rst-test.tsx
- test/shallow-render-utils-test.tsx
- types/preact/index.d.ts
- yarn.lock
Add support for fragments. The handling of fragments differs between full and
shallow rendering in the React adapters. In "mount"/full renders fragments do
not appear in the RST tree. In shallow renders they do.
This implementation follows the pattern of the full renderers in omitting
fragments from the returned RST tree.
Given a structure like:
```
<ul>
<Fragment>
<li/>
<Fragment>
<li/>
</Fragment>
</Fragment>
</ul>
```
The returned RST tree will look like:
```
<ul>
<li/>
<li/>
</ul>
```
The current implementation has a limitation that the root element passed to the
render functions must produce a single RST node. This means that it must either
not be a fragment, or must be a fragment that produces only one child.
Supporting multi-child fragments requires additional work to support the …
> Support fragments

- CHANGELOG.md
- src/MountRenderer.ts
- src/ShallowRenderer.ts
- src/StringRenderer.ts
- src/util.ts
- test/MountRenderer_test.tsx
- test/integration_test.tsx
- types/enzyme/index.d.ts
In order to make error simulation behave realistically, the
implementation works by temporarily patching the instance's `render`
function with a stub that throws the target exception and then forcing a
re-render. After the render, the stub is removed.
Also fix a bug in testing whether anything was rendered when calling
`MountRenderer#getNode`. It is possible in Preact 10 for a component to
produce no DOM output, so we have to check for metadata on the container
instead.
> Support simulating errors in full and shallow rendering

- CHANGELOG.md
- src/ShallowRenderer.ts
- src/compat.ts
- src/preact-rst.ts
- src/preact10-rst.ts
- src/shallow-render-utils.ts
- src/util.ts
- test/init.ts
- test/integration_test.tsx
- test/shallow-render-utils-test.tsx
This PR implements two changes to shallow rendering to make the behaviour more consistent with how it works in React. See commit messages for details.
> Make shallow-rendering behaviour more consistent with React

- CHANGELOG.md
- src/PreactAdapter.ts
- src/preact10-rst.ts
- test/integration_test.tsx
- test/preact-rst-test.tsx
- types/enzyme/index.d.ts
Implement the `elementToNode` adapter method. This enables the adapter to support Enzyme wrapper methods which take an element tree as an argument and need to convert it to an RST node for comparison with the rendered tree. For example, `wrapper.contains(<element tree>)`.
> Support methods of Enzyme wrappers which accept JSX trees as arguments

- .travis.yml
- package.json
- src/MountRenderer.ts
- src/compat.ts
- src/preact-internals.ts
- src/preact10-rst.ts
- src/shallow-render-utils.ts
- src/util.ts
- test/MountRenderer_test.tsx
- test/integration_test.tsx
- test/shallow-render-utils-test.tsx
- yarn.lock
Update the adapter to support the current Preact 10 alpha. See commit message for details. Now that the alpha has been published, also run the tests against Preact 10 on Travis.
> Update Preact 10 support

- CHANGELOG.md
- package.json
- yarn.lock
Also fix a typo in the version number, which failed to break the CI
build!
> Mark Preact 10 as a dev dependency rather than a runtime dependency

- .travis.yml
- package.json
- src/MountRenderer.ts
- src/compat.ts
- src/preact-internals.ts
- src/preact-rst.ts
- src/preact10-rst.ts
- src/preact8-internals.ts
- src/shallow-render-utils.ts
- src/util.ts
- test/init.ts
- test/shallow-render-utils-test.tsx
- yarn.lock
This PR isolates access to internal/private properties of Preact VNodes, components and DOM elements in {preact, preact8}-internals.ts. The fact that the adapter relies on this access is a risk because the names could change or properties could be removed between non-major releases. Isolating this access is a step towards finding a way to avoid it altogether or at least making it easy to keep up with any changes.
> Encapsulate access to Preact internals

- src/MountRenderer.ts
- src/compat.ts
- src/preact10-internals.ts
- src/preact10-rst.ts
- src/preact8-internals.ts
- test/shallow-render-utils-test.tsx
Split the function for accessing VNode rendered into a container and
getting the last vnode rendered by a component into two separate
functions. Although these happen to use the same code, they are logically
different operations. This also provides an opportunity to improve the
names to clarify how they are used.
Also remove access to the `__v` property of Component instances which
was not necessary as the code that called this function already had that
VNode available.
> Rename functions for accessing render output

- CHANGELOG.md
- README.md
- src/Adapter.ts
- src/index.ts
- test/Adapter_test.tsx
- test/integration_test.tsx
Rename the main export for consistency with the React adapter packages.
This should make it possible to use this library slightly more easily as
a drop-in replacement for the Enzyme React adapters.
The export is also aliased to the previous name for backwards
compatibility.
> Rename the package's main export to Adapter

- CHANGELOG.md
- src/index.ts
- src/preact10-rst.ts
Make the adapter a better drop-in replacement for the enzyme-adapter-react-* packages by:
- Making the adapter class the default export of the package
- Fixing an issue with apps or libraries using preact/compat rather than preact directly
> Fix compatibility with preact/compat

- CHANGELOG.md
- src/Adapter.ts
- test/integration_test.tsx
The output is not what would intuitively be expected, but it matches the
outputs from the React adapter and is better than not crashing.
> Fix exception when `wrapper.text()` is called on a text node wrapper

- src/compat.ts
preact/debug "warns" (currently, throws an error) when accessing
Preact 8 VNode properties (attributes, children, nodeName), so avoid
doing this in the `childElements` helper.
> Fix "warning" when accessing vnode.children in Preact 10

- src/Adapter.ts
- src/MountRenderer.ts
- test/MountRenderer_test.tsx
- test/integration_test.tsx
- types/enzyme/index.d.ts
This enables rendering into an existing DOM container element.
See https://airbnb.io/enzyme/docs/api/mount.html#mountnode-options--reactwrapper
> Support `attachTo` option for mount rendering

- src/MountRenderer.ts
- test/MountRenderer_test.tsx
- test/init.ts
Flush any effects scheduled with `useEffect` using the `act` helper
on the initial render.
This means that in a test a developer can write:
```js
const wrapper = mount(<ComponentThatUsesEffects/>)
```
And know that effects will have been run before they start interacting
with the result wrapper.
See https://github.com/airbnb/enzyme/pull/2034 for corresponding change
to the React adapter.
> Flush effects after initial render

- src/MountRenderer.ts
- test/MountRenderer_test.tsx
Discussions on the Enzyme repo suggest that `simulate(...)` is a
semi-deprecated API, but it is the obvious way to dispatch an event
according to the docs and still the most convenient way to do so.
Flushing state updates and effects after a simulated event dispatch
avoids confusion for users about why their component hasn't updated.
> Flush state updates and effects after simulated events

- package.json
- src/preact10-rst.ts
- test/preact-rst-test.tsx
Fix an exception when determining the type of a component if the
component was declared with an arrow function. Native (untranspiled)
arrow functions do not have a `prototype` property.
The existing tests would have encountered the issue, except that they
used the same transpilation settings (to ES5) as for distribution.
Fixes #37
> Fix exception when determining type of arrow function component

- package.json
- src/preact10-rst.ts
- yarn.lock
The tests are currently failing because some DOM vnodes with no children have
a `_children` property equal to `[ null ]` (array with a single `null`
entry) rather than `null`. I need to work out whether this is
expected or a bug in Preact.
> Upgrade Preact 10

- package.json
- test/init.ts
- yarn.lock
This required a work-around for https://github.com/preactjs/preact/issues/1612 which is fixed in the next release.
> Upgrade Preact 10 to 10.0.0-beta.1

- package.json
- src/preact10-rst.ts
- yarn.lock
The representation of text nodes changed from 10.0.0-beta.1 to 10.0.0-beta.2.
- The `text` property ~~may not be missing entirely rather than just `null`~~ is missing entirely
- Text nodes are now represented as vnodes with type `null` and `vnode.props` equal to the string or number value
This PR is backwards-compatible with earlier betas.
Fixes #48
> Update Preact 10 to 10.0.0-beta.2

- src/MountRenderer.ts
- src/ShallowRenderer.ts
- src/StringRenderer.ts
- types/enzyme/index.d.ts
- yarn.lock
An incorrect implementation of the shallow rendering APIs caused this adapter not to work with Enzyme 3.10. See first commit message for details.
> Support Enzyme v3.10

- src/compat.ts
- src/preact10-internals.ts
- src/preact10-rst.ts
- test/shallow-render-utils-test.tsx
https://github.com/preactjs/preact/pull/1658 made some changes to the vnode/component tree for the next release. This PR makes the tests run against a current build of Preact 10 from master as well as the already-released beta 2.
When Preact 10 becomes the stable release, we can drop any code paths that are specific to earlier betas.
See the first commit message for more details.
**TODO**
> Add support for VNode tree changes coming in next Preact 10 release

- package.json
- src/MountRenderer.ts
- src/ShallowRenderer.ts
- src/debounce-render-hook.ts
- test/MountRenderer_test.tsx
- test/integration_test.tsx
- yarn.lock
In the browser, calls to `setState` within a single turn of the event loop are by default batched by Preact and scheduled to be applied using a method equivalent to [queueMicrotask](https://www.chromestatus.com/feature/5111086432911360). React v16 on the other hand batches `setState` calls [within an event handler](https://reactjs.org/docs/faq-state.html#when-is-setstate-asynchronous) and executes them immediately otherwise. React is planning on batching by default [in future](https://stackoverflow.com/questions/48563650/does-react-keep-the-order-for-state-updates/48610973#48610973) as well.
The Enzyme adapter used to change Preact's behavior to make it consistent with React. This had several issues:
- When using hooks together with [the recommended pattern for updating state in response …
> Defer pending updates until Enzyme wrapper is updated

- .gitignore
- package.json
- yarn.lock
Set up code coverage reporting to help identify missing tests. ts-node was switched to transpile-only mode to speed up running tests. Types are still checked when running `yarn build`.
> Set up code coverage reporting

- package.json
- yarn.lock
The work to support the vnode tree changes in this release were already done in https://github.com/preactjs/enzyme-adapter-preact-pure/pull/55.
> Upgrade Preact 10 to 10.0.0-beta.3

- test/MountRenderer_test.tsx
An `act` call is not needed here as Preact runs these effects
synchronously when a component is unmounted.
> Add a test to verify that `MountRenderer#unmount` runs cleanup effects

- package.json
- src/compat.ts
- src/debounce-render-hook.ts
- src/preact8-internals.ts
- yarn.lock
The workaround caused problems in environments where mutating package
exports is prevented. See https://github.com/preactjs/enzyme-adapter-preact-pure/issues/68
I've also upgraded Preact v8 to the latest v8.x release.
Fixes #68
> Upgrade Preact 10 to latest RC and remove workaround for beta releases

- package.json
- src/MountRenderer.ts
- yarn.lock
`forceUpdate` is asynchronous in Preact 10.0.0, in the same way as
`setState`. Therefore we need to wrap it in an `act` call to trigger it
synchronously.
> Update to Preact 10.0.0 and fix `wrapper.simulateError`

- .travis.yml
- package.json
- src/Adapter.ts
- src/MountRenderer.ts
- src/compat.ts
- src/preact10-rst.ts
- src/preact8-rst.ts
- test/Adapter_test.tsx
- test/MountRenderer_test.tsx
- test/init.ts
- test/integration_test.tsx
- test/preact-rst-test.tsx
- test/shallow-render-utils-test.tsx
- tsconfig.json
- types/preact/index.d.ts
- yarn.lock
This PR makes Preact 10 the "default" version internally. This means:
- The "preact" dependency is now 10.0.0 and Preact 8 is imported as an alias
- Commands like `yarn test` test against Preact 10 rather than Preact 8. `yarn test:preact8` will test against Preact 8.
- The TypeScript code is written against the Preact 10 typings, with some extensions to support compiling Preact v8 in `types/preact`
Eventually Preact 8 support will be dropped in a major release, although there is no urgency on that and I expect to keep it around in master for a while. To make that easier, the `rstNodeFromElement` internal helper has been split into separate functions for Preact v8 and Preact v10, and a codepaths that were version-specific have been modified to make that more obvious.
There should be no …
> Make Preact 10 the default version in the code

- package.json
We are sticking with preact-render-to-string v4 to preserve behavior for
Preact v8 + Preact v10. We can reconsider upgrading as part of a
breaking change for one or both of those Preact versions.
See commands in `src/StringRenderer.ts`.
> Ignore preact-render-to-string updates

- src/Adapter.ts
- src/shallow-render-utils.ts
- test/integration_test.tsx
Fix an exception that occurred when shallow rendering stubs a component
that takes a function as the `children` prop. This can happen for
components that implement the "render prop" [1] pattern.
[1] https://reactjs.org/docs/render-props.html
> Fix an exception with render-prop pattern and shallow rendering

- src/shallow-render-utils.ts
- test/integration_test.tsx
I recently upgraded the version of the adapter on a local project of mine and immediately noticed that my snapshot tests were failing for a very specific bit of the codebase. This bit of code in particular was generating component instances using the `preact.h` method directly from a json serialization.
What I managed to track down is that, when doing `h(Foo, null, Child1, Child2)` the children object received in `ShallowRenderStub` is actually an array of the child components. I believe changing `isRenderable` to allow arrays to passthrough should be fine and restore the previous behaviour.
> Fix regression with array children when using the preact h function directly

- src/shallow-render-utils.ts
- test/integration_test.tsx
I have upgraded from 2.2.0 and encountered problems with stubbed out child components no longer containing children in snapshots. Some of this has been already solved by @d3x7r0 in #119, but we also have some components that contain a number as it's only child, and those wouldn't pass through `isRenderable` either.
(The non-JSX component test might be redundant now, since the same problem happens with JSX and multiple children too.)
> Handle all types of children

- src/MountRenderer.ts
This was intended to work, but the Object.assign() fails because, at least in JSDOM, `Event.prototype.bubbles` is only a getter.
> Bugfix: allow simulate('x', { bubbles: true })

- src/MountRenderer.ts
- test/MountRenderer_test.tsx
- test/integration_test.tsx
Support the `invoke` API [1] introduced in Enzyme v3.11.0 that invokes a
prop function within an `act` call and then updates the wrapper afterwards.
Currently `invoke` is only supported _by this adapter_ in `mount` rendering. (Edit: Clarified that this is a limitation of this adapter, not Enzyme generally)
[1] https://github.com/enzymejs/enzyme/blob/master/docs/api/ReactWrapper/invoke.md
> Support `invoke` API

- src/Adapter.ts
- src/MountRenderer.ts
- src/StringRenderer.ts
- src/preact10-rst.ts
- src/util.ts
- test/integration_test.tsx
Make it easier to see where this adapter has a dependency on Enzyme's
implementation vs. just interfaces.
> Use type-only imports from Enzyme where possible

- .gitignore
- package.json
- tsconfig-cjs.json
- tsconfig.json
- yarn.lock
Change the main build to generate ES modules rather than CommonJS. The
CommonJS build is still generated for backwards compatibility and will
be removed in a future major release.
The tests currently use the CommonJS build because that was easier to
get working. They should be changed to use the ESM build in future.
> Add ES module build

- package.json
This was missed in https://github.com/preactjs/enzyme-adapter-preact-pure/pull/151
> Add CommonJS files to npm package

- package.json
- test/Adapter_test.tsx
- yarn.lock
This fixes an error I observed locally in one test:
```
1) preact10-rst
getNode
returns expected RST node (component that renders children):
TypeError: Found non-callable @@iterator
```
I didn't dig into the exact cause of the above, but the test did not fail when
run recently in CI and I have upgraded to Node v17 locally since. Using
a current version of Preact in tests is a good idea in any case.
In the process another test started failing due to the addition of an
internal ID counter to VNodes. This test was adapted to ignore the field
when comparing values.
> Upgrade Preact dependency used in tests to v10.5.15

- index.d.ts
- package.json
- src/Adapter.ts
- src/MountRenderer.ts
- src/RootFinder.ts
- src/wrapWithWrappingComponent.ts
- test/Adapter_test.tsx
- test/MountRenderer_test.tsx
- test/integration_test.tsx
- yarn.lock
Support for `wrappingComponent` has been requested in https://github.com/preactjs/enzyme-adapter-preact-pure/issues/99 and this PR adds it for components rendered using the `shallow` and `mount` Enzyme utils.
1. I added tests to the project and all are passing.
2. I verified that the changes in this PR solve the issue for my organization, allowing us to use `wrappingComponent` and `wrappingComponentProps` for both `shallow` and `mount` components.
Note for my future self: this is how I verified the changes locally…
- Make sure `yalc` is installed (as recommended in the [contributing guide](https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/CONTRIBUTING.md)): `yarn global add yalc`
- Run `yalc publish` in the (forked) project locally.
- Run this in the other project where …
> Support wrappingComponent & wrappingComponentProps

- package.json
- test/preact-rst-test.tsx
- yarn.lock
This required an @types/jsdom update for compatibility, as well as a
change in a test to avoid a `Found non-callable @iterator` error.
> Upgrade TypeScript to latest release

- package.json
- src/preact10-rst.ts
- tsconfig-cjs.json
- yarn.lock
Set the JS version targeted by the CommonJS build to be the same as the ESM build (ES 2020). This reduces the complexity of the testing matrix.
Also remove the Array.flatMap polyfill. This is included in ES2020 and has been supported natively since Node v11, Chrome 69, Firefox 62 and Safari 12.
> Update CommonJS build target to ES 2020 and remove Array.flatMap polyfill

- src/compat.ts
This was used during the Preact v8 => Preact v10 migration. The
wrapper's types are currently incomplete.
> Remove a currently-unused `render` wrapper

- src/Adapter.ts
This suppresses a TypeScript error when using @types/react v18. See https://github.com/preactjs/enzyme-adapter-preact-pure/issues/161#issuecomment-1097961763.
The @types/react transitive dependency in this package has not yet been
updated because there are TS errors in tests when trying to pass JSX
elements to functions that expect a ReactElement.
```
Type 'VNode<any>' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.
Types of property 'type' are incompatible.
Type 'string | ComponentType<any>' is not assignable to type 'string | JSXElementConstructor<any>'.
Type 'ComponentClass<any, {}>' is not assignable to type 'string | JSXElementConstructor<any>'.
Type 'ComponentClass<any, {}>' is not assignable to type 'new (props: any) => Component<any, any, any>'. …
```
> Add explicit cast from VNode to ReactElement type

- README.md
- src/compat.ts
- src/preact10-rst.ts
- src/shallow-render-utils.ts
- test/init.ts
- test/integration_test.tsx
Preact v10.x has long been the stable version of Preact, so we don't
need to specifically call out the version in various places.
> Change various "Preact 10" references to Preact

- src/MountRenderer.ts
- src/ShallowRenderer.ts
- src/compat.ts
- src/preact10-internals.ts
- src/preact10-rst.ts
- src/shallow-render-utils.ts
- src/util.ts
- test/Adapter_test.tsx
- test/MountRenderer_test.tsx
- test/preact-rst-test.tsx
- test/shallow-render-utils-test.tsx
- test/util-test.tsx
Small PR to consistently use `import type` across the codebase. I found this useful to understand what concrete parts of preact the adapter relies on and what parts of preact are just for types.
> Consistently use `import type`

- .github/workflows/ci.yml
- package.json
Update workflow actions to their latest version and take advantage of new features
> Upgrade workflow actions

- .husky/pre-commit
- package.json
I mistakenly used `npx` to run lint-staged. Since this repo uses yarn, the pre-commit script should too.
> Use yarn to run lint-staged

- CHANGELOG.md
- examples/counter/test/setup.js
- examples/typescript/test/setup.ts
- package.json
- src/Adapter.ts
- src/StringRenderer.ts
- test/MountRenderer_test.tsx
- test/init.ts
- test/integration_test.tsx
- test/jsdom.ts
- yarn.lock
The React adapter's string renderer uses `renderToStaticMarkup` from `react-dom/server` allowing the string render to run in environments without a DOM. This PR adds an option to enable using `preact-render-to-string` for our string renderer to enable our string renderer to also run in environments without a DOM.
The tests for this renderer teardown the JSDOM environment set up for its tests to ensure the adapter with the new flag works in an environment without JSDOM.
> Add option to use `preact-render-to-string` for the StringRenderer

- CHANGELOG.md
- index.d.ts
- src/Adapter.ts
- src/preact10-rst.ts
- src/util.ts
- test/Adapter_test.tsx
- test/integration_test.tsx
- test/preact-rst-test.tsx
- test/shared.tsx
Support more kinds of return types from components, using Preact's `ComponentChild` type as a guide.
Also fixes a bug where `ref` and `key` weren't restored on props in `nodeToElement`.
> Support more component return types

- README.md
- src/Adapter.ts
Update our Readme with documentation on the new options added to the Adapter.
I think the precommit hook also ran Prettier on our Readme
> Document new options in Readme
